### PR TITLE
Add support for WSGI

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [x] Deduplicate the code in `zserver.py` and `wsgi.py` (Not sure what to do with the tests.)
- [x] Add an equivalent to the `ZSERVER` layer and its siblings to `wsgi.py`
- [x] Re-add `z2.py` containing BBB imports from `wsgi.py` but with the names used in `zserver.py` using `zope.deprecation`
- [x] Fix change log entry to describe the changes and the needed actions for consumers of this package.
- [X] ~~Port to Python 3~~ (see #48 contains the port)
- [ ] Get jenkins-job for Plone 5.2 (in Python 2.7) green.

Ready for review.

### CODE REVIEW

**Comment by icemac** [comment]
This PR is now ready for review. I know it breaks some tests in the Plone buildout but this is expected when switching to WSGI by default and "no-op"-ing the FTPServer layer.

**Comment by gforcada** [comment]
@icemac then if this is breaking tests, we need to either branch plone.testing before these pull request, so we can adapt the changes later, or fix them and merge everything together.

**Comment by thet** [comment]
@gforcada @icemac it's fine that this PR is targeting master, as the plone.testing 6.x is targeting only Zope 4.
We need to fix tests in a way that they work with plone.testing 5.x also.

**Comment by icemac** [comment]
What can I do to get this PR merged? It it ready enough to hit the merge button?

**Comment by pbauer** [comment]
I have no looked at this PR but it cannot be merged into master unless the jenkins-job for Plone 5.2 (in Python 2.7) is green.

**Comment by gforcada** [comment]
Most of the errors come from Archetypes... can we deprecate it on the tests already? :-)

**Comment by icemac** [comment]
@gforcada There was consensus at the Zope-4-Welcome-Sprint that these tests cannot be disabled yet as Archetypes is still needed for the migration away from it. This is a story which should not break. I fixed the Archetypes tests against Plone 5.2 in plone/Products.Archetypes#109.

**Comment by icemac** [comment]
This PR is superseded by #48. It requires different changes in `plone.app.testing` than #48 and there is no need to change it twice.

**Comment by gforcada** [comment]
@icemac then this should be closed in favor of #48? :thinking:

**Comment by icemac** [comment]
@gforcada It will be automatically closed when #48 gets merged. (See the description there.)

**Comment by jensens** [comment]
see now all joined in #50

**Pull request closed without merging**
