### PR TITLE
Python 3.6 new

### PR DESCRIPTION
**Pull request by jensens**
So, this is all from #48, plus rebase with master, plus additional changes from last sprints. *sigh* 

It is what is used in Plone 5.2 coredev buildout right now.

In order to merge at least plone.app.testing needs also to be ready.

This really should be addressed and get merged, any input on open todos welcome!
cc pbauer @icemac @loechel 

Closes #48

### CODE REVIEW

**Comment by jensens** [comment]
Lets see what happens with a PR job on 5.2 with
```
https://github.com/plone/plone.testing/pull/50
https://github.com/plone/plone.app.testing/pull/49
```

**Comment by jensens** [comment]
Travis is broken b/c it checks out tons of dependencies. Local tests are green with coredev 5.2.

**Comment by icemac** [comment]
@jensens wrote:
> Lets see what happens with a PR job on 5.2 with
> ```
> https://github.com/plone/plone.testing/pull/50
> https://github.com/plone/plone.app.testing/pull/49
> ```

The result is a bit disappointing: 1185 broken tests. This looks like a problem on a deeper level. I currently do not have the time and energy to look into it.

**Comment by jensens** [comment]
@icemac indeed, no problem, I will take a look soon.

**Pull request merged**
